sources:
  - id: ap-news
    name: Associated Press
    domains: 
      - apnews.com
    retrieval_method: search
    enabled: true
    maximum_articles_per_briefing: 3

  - id: retuers
    name: Reuters
    domains: 
      - reuters.com
    retrieval_method: search
    enabled: true
    maximum_articles_per_briefing: 3

  - id: npr
    name: NPR
    domains: 
      - npr.org
    retrieval_method: rss
    #this is the url where NPR pulishes its news feed
    feed_urls:
      - https://feeds.npr.org/1001/rss.xml
    enabled: true
    maximum_articles_per_briefing: 3  
